
export const level = [
  "P                                                          P",
  "P                                                          P",
  "P                                                          P",
  "P                                                          P",
  "P             F                     PPPPPP       SS        P",
  "P           PPPPPPP                            PPPPPPP     P",
  "P   PPPP                 PPPPPPP                           P",
  "P            SSS                                        PPPP",
  "PPPP    PPPPPPPP                                           P",
  "P                                                PPPP      P",
  "P   PPPP                         PPPPPPP                   P",
  "P                                                          P",
  "P                   SSS                                 PPPP",
  "P      PPPPPP       PPPPPPPPP                PPPPP         P",
  "P                                PPPPPP                 PPPP",
  "P                                                          P",
  "P                                       P                  P",
  "PPPP        PPPPPPPP                     P                 P",
  "P                         PPPPPP          P             PPPP",
  "P                                                          P",
  "PPPP                                  P PPP      PPPP      P",
  "P                                                          P",
  "P             PPPPPPPPP                                    P",
  "PPPP                                                PPPPPPPP",
  "P      PPPP             SSS         PPPPPP                 P",
  "P                                                          P",
  "P                                                          P",
  "P                                                          P",
  "P         PP                 P                PPPPPPPP     P",
  "P        PPPP               PP                             P",
  "P     PPPPPPPPPPP            P                             P",
  "P                            P                             P",
  "P               A     X      P                             P",
  "P               PPPPPPPPPPPPPPP     PPPPPPPPPPPPPPPPP      P",
  "P        SSS                  PP                           P",
  "P    PPPPPPPP                 PPP                          P",
  "P                             PPPP                         P",
  "PPPPPPPPPPPPPPPPPP      PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
  "PPPPPPPPPPPPPPPPPP      PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
  "PPPPPPPPPPPPPPPPPP      PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
  "PPPPPPPPPPPPPPPPPP      PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
  "PPPPPPPPPPPPPPPPPP      PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
  "PPPPPPPPPPPPPPPPPP      PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
  "PPPPPPPPPPPPPPPPPP      PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
  "PPPPPPPPPPPPPPPPPP      PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
  "PPPPPPPPPPPPPPPPPP      PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
  "PPPPPPPPPPPPPPPPPP      PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
  "PPPPPPPPPPPPPPPPPP      PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
];

export const oldTestLevel = [
  "                                                                                                                         ",
  "                                                                                                                         ",
  "                                                                                                                         ",
  "                                                                                                                         ",
  "                                                                                                                         ",
  "                                                                                                                         ",
  "                                                                                                                         ",
  "                                                                                                                         ",
  "                                                                                                                         ",
  "                                                                                                                         ",
  "                                                                                                                         ",
  "                                                                                                                         ",
  "                                                                                                                         ",
  "                                                                                                                         ",
  "                                                                                                                         ",
  "                                                                                                                         ",
  "                                                                                                                         ",
  "                                                                                                                         ",
  "F                                                                                                                        ",
  "PPPPP    PP                                                                                                              ",
  "          P                 P                                                                                            ",
  "           P                PP                                                                                           ",
  "PPPPP        P          P   P  P                                                                                         ",
  "               X                                                                                                         ",
  "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
]

export const rlevel = [
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                          F        ",
  "                        PPP        ",
  "                 P                 ",
  "PPPPP                              ",
  "                   P               ",
  "              P                    ",
  " X   P                             ",
  "PP   P   P  P                      ",
];

export const pathTest = [
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "       P                           ",
  "                                   ",
  "           F                       ",
  "    P      P   PPPPPPP             ",
  "                                   ",
  "P                         P        ",
  "                                   ",
  "                                   ",
  "    P                          P   ",
  "                                   ",
  "                           P       ",
  "  X A  P                           ",
  "  PPP     PPPPPPPPPPPPPPPPPPPP     ",
  "                                   ",
];

export const GameLevel = [
  "                                               ",
  "                                               ",
  "                                               ",
  "                                               ",
  "                                               ",
  "                                               ",
  "                                               ",
  "                                               ",
  "                                               ",
  "       PPPPP                                   ",
  "                                               ",
  "               PPPPPPPP   PPPPP                ",
  "                                               ",
  " PPPPP                                         ",
  "                                               ",
  "                                               ",
  "                                F              ",
  "      PPPPPP                  PPPPP       PP   ",
  "                                         PPP   ",
  "                        PPP             PPPP   ",
  "                                       PPPPP   ",
  " PPPP          PPPPPP                 PPPPPP   ",
  "                                     PPPPPPP   ",
  "     X  A                           PPPPPPPP   ",
  "    PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP   ",
  "                                               ",
  "                                               ",
];

export const vlevel = [
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "                                   ",
  "AX                                F",
  "PP PPPPPPPPPPPPPPPPPPPP           P",
  "                                   ",
];